authors: [kitskub]
main: me.kitskub.flooder.Flooder
name: Flooder
version: '1.0'
depend: [GameLib]
# Commands
commands:
  f:
    description: Flooder user commands
  fa:
    description: Flooder admin commands
# Permission nodes
permissions: